import type { Metadata } from 'next';
import { Poppins } from 'next/font/google'
import '../app/globals.css'
import { DevLinkProvider } from '@/devlink/DevLinkProvider';
import 'react-phone-number-input/style.css'
import Script from 'next/script'


const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['300', '400', '500', '600', '700', '800', '900'], // ✅ all weights
  subsets: ['latin'],
  display: 'swap', // optional but recommended for performance
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${poppins.className} `}>
        <DevLinkProvider>
          {/* Add here any Navbar or Header you want to be present on all pages */}
          {children}
          {/* Add here any Footer you want to be present on all pages */}
        </DevLinkProvider>
      </body>
      <Script
        src={`https://www.googletagmanager.com/gtag/js?id=G-QRV66J4E1V`}
        strategy="afterInteractive"
      />

      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-QRV66J4E1V', {
            page_path: window.location.pathname,
          });
        `}
      </Script>
    </html>
  )
}
