import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../app/globals.css'
import { DevLinkProvider } from '@/devlink/DevLinkProvider'
import 'react-phone-number-input/style.css'
import Script from 'next/script'
import ClarityProvider from './components/Clarity/Clarity'
const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['300', '400', '500', '600', '700', '800', '900'], // ✅ all weights
  subsets: ['latin'],
  display: 'swap', // optional but recommended for performance
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${poppins.className} `}>
        <ClarityProvider />
        <DevLinkProvider>
          {/* Add here any Navbar or Header you want to be present on all pages */}
          {children}
          {/* Add here any Footer you want to be present on all pages */}
          <Script id="clarity" strategy="afterInteractive">
            {`
            (function (c, l, a, r, i, t, y) {
    c[a] =
      c[a] ||
      function () {
        (c[a].q = c[a].q || []).push(arguments);
      };
    t = l.createElement(r);
    t.async = 1;
    t.src = 'https://www.clarity.ms/tag/' + i;
    y = l.getElementsByTagName(r)[0];
    y.parentNode.insertBefore(t, y);
  })(window, document, 'clarity', 'script', 'v8gsdlcfcp');
          `}
          </Script>
          <Script id="meta-pixel" strategy="afterInteractive">
            {`
           !function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '1308698014213503');
fbq('track', 'PageView');
          `}
          </Script>
          <noscript>
            <img
              height="1"
              width="1"
              style={{ display: 'none' }}
              src="https://www.facebook.com/tr?id=1308698014213503&ev=PageView&noscript=1"
            />
          </noscript>

          <Script
            src={`https://www.googletagmanager.com/gtag/js?id=G-QRV66J4E1V`}
            strategy="afterInteractive"
          />

          <Script id="google-analytics" strategy="afterInteractive">
            {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-QRV66J4E1V', {
            page_path: window.location.pathname,
          });
        `}
          </Script>
        </DevLinkProvider>
      </body>
    </html>
  )
}
